export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const CREATE_MEDICINE_REQUEST = 'CREATE_MEDICINE_REQUEST';
export const CREATE_MEDICINE_SUCCESS = 'CREATE_MEDICINE_SUCCESS';
export const CREATE_MEDICINE_FAIL = 'CREATE_MEDICINE_FAIL';

export const DELETE_MEDICINE_REQUEST = 'DELETE_MEDICINE_REQUEST';
export const DELETE_MEDICINE_SUCCESS = 'DELETE_MEDICINE_SUCCESS';
export const DELETE_MEDICINE_FAIL = 'DELETE_MEDICINE_FAIL';

export const UPDATE_MEDICINE_REQUEST = 'UPDATE_MEDICINE_REQUEST';
export const UPDATE_MEDICINE_SUCCESS = 'UPDATE_MEDICINE_SUCCESS';
export const UPDATE_MEDICINE_FAIL = 'UPDATE_MEDICINE_FAIL';

export const GET_ALL_MEDICINE_REQUEST = 'GET_ALL_MEDICINE_REQUEST';
export const GET_ALL_MEDICINE_SUCCESS = 'GET_ALL_MEDICINE_SUCCESS';
export const GET_ALL_MEDICINE_FAIL = 'GET_ALL_MEDICINE_FAIL';

export const GET_MEDICINE_PHOTO_REQUEST = 'GET_MEDICINE_REQUEST';
export const GET_MEDICINE_PHOTO_SUCCESS = 'GET_MEDICINE_SUCCESS';
export const GET_MEDICINE_PHOTO_FAIL = 'GET_MEDICINE_FAIL';

export const GET_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';

export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAIL = 'GET_COMPANY_FAIL';

export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_FAIL = 'CREATE_COMPANY_FAIL';

export const DELETE_COMPANY_REQUEST = 'DELETE_COMPANY_REQUEST';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_FAIL = 'DELETE_COMPANY_FAIL';

export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';
