export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CREATE_MEDICINE_REQUEST = 'CREATE_MEDICINE_REQUEST';
export const CREATE_MEDICINE_SUCCESS = 'CREATE_MEDICINE_SUCCESS';
export const CREATE_MEDICINE_FAIL = 'CREATE_MEDICINE_FAIL';

export const GET_ALL_MEDICINE_REQUEST = 'GET_ALL_MEDICINE_REQUEST';
export const GET_ALL_MEDICINE_SUCCESS = 'GET_ALL_MEDICINE_SUCCESS';
export const GET_ALL_MEDICINE_FAIL = 'GET_ALL_MEDICINE_FAIL';

export const GET_MEDICINE_PHOTO_REQUEST = 'GET_MEDICINE_REQUEST';
export const GET_MEDICINE_PHOTO_SUCCESS = 'GET_MEDICINE_SUCCESS';
export const GET_MEDICINE_PHOTO_FAIL = 'GET_MEDICINE_FAIL';

export const GET_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAIL = 'GET_COMPANY_FAIL';
